spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa-0909--1?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    #update：最常用的属性，第一次加载 hibernate 时根据 model 类会自动建立起表的结 构（前提是先建立好数据库）
    #以后加载 hibernate 时根据 model 类自动更新表结构，即使 表结构改变了但表中的行仍然存在不会删除以前的行
    #要注意的是当部署到服务器后，表结 构是不会被马上建立起来的，是要等应用第一次运行起来后才会